name: fitdesk

environment:
  sdk: ">=3.0.0"

dependencies:
  aws_dynamodb_api: ^2.0.0
  aws_iot_api: ^2.0.0
  aws_iot_data_api: ^2.0.0
  aws_lambda_dart_runtime:
  aws_sqs_api: ^2.0.0
  livekit_server_sdk: ^1.0.0
  nanoid: ^1.0.0
  sentry: ^8.5.0
  http:
  aws_ses_api: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
