name: Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug runner
        run: |
          echo "Runner: $RUNNER_NAME"
          uname -a
          env

      - uses: dart-lang/setup-dart@v1

      - name: Install Dart deps
        run: |
          cd dart
          dart pub get

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::245991315644:role/Github_Deploy
          aws-region: eu-central-1

      - name: Deploy Dart
        run: |
          cd dart
          mkdir -p target/dev
          mkdir build
          dart compile exe lib/main.dart -o build/bootstrap --define "LIVE_KIT_API_SECRET=prova"
          cd build
          zip bootstrap.zip ./*
          cd ..
          npm i serverless@3.39.0
          npm i serverless-iam-roles-per-function
          npm i serverless-prune-plugin
          npx serverless deploy --verbose --param "aws_region=eu-central-1"

  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug runner
        run: |
          echo "Runner: $RUNNER_NAME"
          uname -a
          env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::245991315644:role/Github_Deploy
          aws-region: eu-central-1

      - name: Deploy Typescript
        run: |
          cd ts
          npm install
          npx serverless deploy --conceal
